// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClnqwn-_nnM96XorJiarJxC4gKSSzKoDA',
    appId: '1:69528103393:web:c60acbc82f7002c7a90aa0',
    messagingSenderId: '69528103393',
    projectId: 'kosmetic-6171c',
    authDomain: 'kosmetic-6171c.firebaseapp.com',
    storageBucket: 'kosmetic-6171c.firebasestorage.app',
    measurementId: 'G-N8RPWFDDHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwxESbd2NbAlCWMxnvGev9NVupzBfdTUg',
    appId: '1:69528103393:android:e112b6f1555ddcb2a90aa0',
    messagingSenderId: '69528103393',
    projectId: 'kosmetic-6171c',
    storageBucket: 'kosmetic-6171c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsqhLw-JQyWVLbV3QgQqMdjOmrDgpW40s',
    appId: '1:69528103393:ios:be3f38705ded87faa90aa0',
    messagingSenderId: '69528103393',
    projectId: 'kosmetic-6171c',
    storageBucket: 'kosmetic-6171c.firebasestorage.app',
    iosBundleId: 'com.esma.projectOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsqhLw-JQyWVLbV3QgQqMdjOmrDgpW40s',
    appId: '1:69528103393:ios:be3f38705ded87faa90aa0',
    messagingSenderId: '69528103393',
    projectId: 'kosmetic-6171c',
    storageBucket: 'kosmetic-6171c.firebasestorage.app',
    iosBundleId: 'com.esma.projectOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClnqwn-_nnM96XorJiarJxC4gKSSzKoDA',
    appId: '1:69528103393:web:35b0ac373b9c6687a90aa0',
    messagingSenderId: '69528103393',
    projectId: 'kosmetic-6171c',
    authDomain: 'kosmetic-6171c.firebaseapp.com',
    storageBucket: 'kosmetic-6171c.firebasestorage.app',
    measurementId: 'G-DPN35KQBYH',
  );
}
